/*
 * Copyright (c) 2014  Akila Ranasinghe </ SPYD3R-X >
 * All rights reserved.
 * GitHub: https://github.com/SPYD3R-X
 * 03 Oct 2014 07:02:20 PM By AKILA.
 */
package UI;

import java.awt.Color;
import java.io.BufferedInputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author AKILA
 */
public class PowerOptions_UI extends javax.swing.JFrame {

    /**
     * Creates new form PowerOptions_UI
     */
    public PowerOptions_UI() {
        initComponents();
        setico();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Button_Restart = new javax.swing.JButton();
        Button_ShutDown = new javax.swing.JButton();
        Button_Hibernate = new javax.swing.JButton();
        lbl_Restart = new javax.swing.JLabel();
        lbl_ShutDown = new javax.swing.JLabel();
        lbl_Hibernate = new javax.swing.JLabel();
        btn_SetTimer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_info = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Power Options");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        Button_Restart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restart.png"))); // NOI18N
        Button_Restart.setContentAreaFilled(false);
        Button_Restart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Restart.setFocusPainted(false);
        Button_Restart.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Restart2.png"))); // NOI18N
        Button_Restart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_RestartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_RestartMouseExited(evt);
            }
        });
        Button_Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RestartActionPerformed(evt);
            }
        });

        Button_ShutDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Shutdown.png"))); // NOI18N
        Button_ShutDown.setContentAreaFilled(false);
        Button_ShutDown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_ShutDown.setFocusPainted(false);
        Button_ShutDown.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutdown2.png"))); // NOI18N
        Button_ShutDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_ShutDownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_ShutDownMouseExited(evt);
            }
        });
        Button_ShutDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ShutDownActionPerformed(evt);
            }
        });

        Button_Hibernate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hibernate.png"))); // NOI18N
        Button_Hibernate.setContentAreaFilled(false);
        Button_Hibernate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Hibernate.setFocusPainted(false);
        Button_Hibernate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hibernate2.png"))); // NOI18N
        Button_Hibernate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_HibernateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_HibernateMouseExited(evt);
            }
        });
        Button_Hibernate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HibernateActionPerformed(evt);
            }
        });

        lbl_Restart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Restart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Restart.setText("Restart");

        lbl_ShutDown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ShutDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ShutDown.setText("Shutdown");

        lbl_Hibernate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Hibernate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Hibernate.setText("Hibernate");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Restart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Restart, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_ShutDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ShutDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_Hibernate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Hibernate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Button_Hibernate, Button_Restart, Button_ShutDown, lbl_Hibernate, lbl_Restart, lbl_ShutDown});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_ShutDown, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(Button_Hibernate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Restart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Restart)
                    .addComponent(lbl_ShutDown)
                    .addComponent(lbl_Hibernate))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Button_Hibernate, Button_Restart, Button_ShutDown});

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 280, 120));

        btn_SetTimer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_SetTimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock1.png"))); // NOI18N
        btn_SetTimer.setText("Set Timer ");
        btn_SetTimer.setContentAreaFilled(false);
        btn_SetTimer.setFocusable(false);
        btn_SetTimer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_SetTimer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_SetTimer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clock2.png"))); // NOI18N
        btn_SetTimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SetTimerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SetTimerMouseExited(evt);
            }
        });
        btn_SetTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SetTimerActionPerformed(evt);
            }
        });
        jPanel3.add(btn_SetTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaper.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -8, 350, 210));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/information.png"))); // NOI18N
        btn_info.setBorderPainted(false);
        btn_info.setContentAreaFilled(false);
        btn_info.setFocusPainted(false);
        btn_info.setFocusable(false);
        btn_info.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/information_2.png"))); // NOI18N
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 40, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Power Options");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Title_back.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RestartActionPerformed

        int op = JOptionPane.showConfirmDialog(rootPane, "Do You Want to Restart Now", "Restart", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            try {
                // Restart
                Runtime r = Runtime.getRuntime();
                r.exec("shutdown -r -t 0");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Button_RestartActionPerformed

    private void Button_ShutDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ShutDownActionPerformed

        int op = JOptionPane.showConfirmDialog(rootPane, "Do You Want to Shutdown Now", "Shutdown", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            try {
                // Shutdown
                Runtime r = Runtime.getRuntime();
                r.exec("shutdown -s -t 0");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Button_ShutDownActionPerformed

    private void Button_HibernateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HibernateActionPerformed

        int op = JOptionPane.showConfirmDialog(rootPane, "Do You Want to Hibernate Now", "Hibernate", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            try {
                // Hibernate
                Runtime r = Runtime.getRuntime();
                r.exec("shutdown -h");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Button_HibernateActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed

        new About(this, true).setVisible(true);
    }//GEN-LAST:event_btn_infoActionPerformed

    private void Button_RestartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_RestartMouseEntered

        lbl_Restart.setForeground(Color.BLUE);
    }//GEN-LAST:event_Button_RestartMouseEntered

    private void Button_RestartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_RestartMouseExited

        lbl_Restart.setForeground(Color.BLACK);
    }//GEN-LAST:event_Button_RestartMouseExited

    private void Button_ShutDownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ShutDownMouseEntered

        lbl_ShutDown.setForeground(Color.BLUE);
    }//GEN-LAST:event_Button_ShutDownMouseEntered

    private void Button_ShutDownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ShutDownMouseExited

        lbl_ShutDown.setForeground(Color.BLACK);
    }//GEN-LAST:event_Button_ShutDownMouseExited

    private void Button_HibernateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_HibernateMouseEntered

        lbl_Hibernate.setForeground(Color.BLUE);
    }//GEN-LAST:event_Button_HibernateMouseEntered

    private void Button_HibernateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_HibernateMouseExited

        lbl_Hibernate.setForeground(Color.BLACK);
    }//GEN-LAST:event_Button_HibernateMouseExited

    private void btn_SetTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SetTimerActionPerformed

        new Settings_UI(this, true).setVisible(true);

    }//GEN-LAST:event_btn_SetTimerActionPerformed

    private void btn_SetTimerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SetTimerMouseEntered

        btn_SetTimer.setForeground(Color.BLUE);
    }//GEN-LAST:event_btn_SetTimerMouseEntered

    private void btn_SetTimerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SetTimerMouseExited

        btn_SetTimer.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_SetTimerMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerOptions_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PowerOptions_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Button_Hibernate;
    public static javax.swing.JButton Button_Restart;
    public static javax.swing.JButton Button_ShutDown;
    public static javax.swing.JButton btn_SetTimer;
    public static javax.swing.JButton btn_info;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Hibernate;
    private javax.swing.JLabel lbl_Restart;
    private javax.swing.JLabel lbl_ShutDown;
    // End of variables declaration//GEN-END:variables

    private void setico() {
        try {
            setIconImage(ImageIO.read(new BufferedInputStream(getClass().getResourceAsStream("/Images/Shutdown.png"))));
        } catch (Exception e) {
        }
    }

}
